### ISSUE TITLE
Restringir limite de saque por categoria

### ISSUE THREAD

**Issue by erickpintor** [erickpintor/ExercicioRefatoracaoBanco#3]
ATENCAO: contas Silver possuem um limite diário de R$ 10000,00 para saques; contas Gold possuem um limite diário de R$ 100000,00 para saques; contas Platinum possuem um limite diário de 500000,00 para saques. <<< ESTAS RESTRIÇÕES AINDA NÃO ESTÃO IMPLEMENTADAS !!

**Comment by gustavohd18** [comment]
como fica esse limite diário, pois posso realizar ele apenas na memória, onde que se abrir novamente o programa o mesmo reinicia o limite diário, outra forma dai mesmo que ele saia do sistema é pegar sempre a ultima operação de debito da conta assim se o dia dela for o mesmo dia do sistema pego este valor da operação como parametro, posso implementar as 2 opções e analisamos depois qual das 2 seria a melhor.

**Comment by erickpintor** [comment]
Vamos focar na refatoração. Depois olhamos pra isso.
